services:
  ubuntu-back:
    image: dockerfrancisx/ubuntu:latest
    ports:
      - "8080:8080"
    env_file:
      - variables.env
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:18
    env_file:
      - variables.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U $${POSTGRES_USERNAME} -d $${POSTGRES_DB} || exit 1" ]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 5s
    restart: always
  ubuntu-front:
    image: dockerfrancisx/ubuntu-front:latest
    ports:
      - "80:80"
    depends_on:
      - ubuntu-back
    restart: always
